services:
  - type: web
    name: connectspace-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: connectspace-backend
          property: port
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # Set this manually in Render dashboard
    autoDeploy: true
    branch: main
    rootDir: ./
    
  # Optional: Static site service for frontend (alternative to Netlify)
  - type: static
    name: connectspace-frontend
    buildCommand: echo "Static files ready"
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    branch: main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html